### ISSUE TITLE
1.4.0 merged but not available

### ISSUE THREAD

**Issue by martinfleis** [conda-forge/contextily-feedstock#21]
We have merged #20 a few days ago. The CI on the PR passed but the subsequent action [failed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=796215&view=results). As a result, 1.4.0 is still [not available ](https://prefix.dev/channels/conda-forge/packages/contextily)to download, which is causing issues due to Stamen tiles deprecation which is done by mixing tile dimensions, breaking contextily in process.

@ocefpaf are you aware of any smart bot command that could fix it? Should I just open a PR bumping only the build number?

**Comment by ocefpaf** [comment]
I restarted the CIs manually and it seems to be now: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=653955&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97

The package should be in the channel shortly. Please let me know if it isn't..

**Comment by jorisvandenbossche** [comment]
@ocefpaf can you restart CI because of some more admin rights? Because I was looking for that 15min ago, but didn't find any button .. (I was thinking because of being maintainer of this feedstock, I would be able to do that)

**Comment by jorisvandenbossche** [comment]
And thanks for doing that! ;)

**Comment by ocefpaf** [comment]
> @ocefpaf can you restart CI because of some more admin rights? Because I was looking for that 15min ago, but didn't find any button .. (I was thinking because of being maintainer of this feedstock, I would be able to do that)

Azure+GH is odd. You should be able to but that is not the first time a maintainer complains about that. When. That happens, if I'm not around to restart, the best option is to push an empty commit or ask the bot to rerender.
