### ISSUE TITLE
Making contextily 1.0rc1 available on coda-forge

### ISSUE THREAD

**Issue by darribas** [conda-forge/contextily-feedstock#6]
Earlier this week, I pushed a new RC of contextily to PyPi:

https://pypi.org/project/contextily/1.0rc1/

Would it be possible to make it available through conda-forge @ocefpaf? I'm happy to do the work necessary, but I've never done it and I'm not sure what's required.

**Comment by ocefpaf** [comment]
@darribas we usually put RCs on a dev label but that can be awkward to install, it would be something like:

```
conda install conda-forge/label/dev::contextily
```

I guess it is OK to break that rule here and have this version in the main channel for convenience. See #8

**Comment by darribas** [comment]
Thank you very much @ocefpaf!!! I'd worked around by installing contextily on conda, then running a `pip install -U contextily==1.0rc1` because dependencies are unchanged. But this is great!!!

**Comment by ocefpaf** [comment]
>  I'd worked around by installing contextily on conda, then running a pip install -U contextily==1.0rc1 because dependencies are unchanged

When doing that use `--no-deps` to prevent `pip` from clobbering the installed dependencies, which can be troublesome sometimes.
